# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steve Matsumoto's Website
email: steve@stevematsumoto.net
description: > # this means to ignore newlines until "baseurl:"
  I'm Stephanos (Steve) Matsumoto, a computer scientist of many interests. This
  is my personal page, which contains blog posts, a description of my projects,
  and lots of other goodies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: smaptas
github_username: syclops

# Build settings
markdown: kramdown
